// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaBylnPQ-0Dr_znSjs2IIOWmD60BtQnY',
    appId: '1:53239051223:web:4648e3dd1ee52d646dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    authDomain: 'mobalworld.firebaseapp.com',
    storageBucket: 'mobalworld.appspot.com',
    measurementId: 'G-04D8MB9GLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8bN2fhugKeuTZRBNXp81x9FFIkGWqAs',
    appId: '1:53239051223:android:a62d30c44b7434146dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7X5jqv0OpU0d8q9VztCWXuWgf2XOt6Dg',
    appId: '1:53239051223:ios:9c7d3c97c0f375686dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
    iosClientId: '53239051223-crivsh8jjdkdp1fsvc37rged8gj4d874.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7X5jqv0OpU0d8q9VztCWXuWgf2XOt6Dg',
    appId: '1:53239051223:ios:22baef62ad88593f6dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
    iosClientId: '53239051223-aleit5k86ab4n8uoe26e85tv04bup3b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobal.RunnerTests',
  );
}
